name: Build and Publish ACB DRE Table

on:
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * 1"

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: "release"

      - name: Cache R packages
        uses: actions/cache@v4
        with:
          path: ~/.cache/R
          key: ${{ runner.os }}-r-${{ hashFiles('scripts/*.R') }}
          restore-keys: |
            ${{ runner.os }}-r-

      - name: Install required packages
        run: |
          .libPaths("~/.cache/R")

          pkgs <- c(
            "tidyverse",
            "janitor",
            "reactable",
            "htmltools",
            "glue",
            "lubridate"
          )

          to_install <- setdiff(pkgs, installed.packages()[,"Package"])
          if (length(to_install) > 0) install.packages(to_install)
        shell: Rscript {0}

      - name: Install Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render QMD
        run: |
          export R_LIBS_USER=$HOME/.cache/R
          quarto render tabla_dre.qmd

      - name: Publish to Quarto Pub
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: quarto-pub
          path: .
          render: false
        env:
          QUARTO_PUB_TOKEN: ${{ secrets.QUARTO_PUB_TOKEN }}
